# Generated by Django 5.2.3 on 2025-06-18 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 18, 23, 16, 2, 611757, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
